version: '3'
services:
  web:
    image: nginx:1.21.6
    container_name: nt_nginx
    ports:
       - "8888:80"
       - "8833:443"
    volumes:
    - ./conf/nginx.conf:/etc/nginx/nginx.conf
    - ./certs:/etc/nginx/certs:rw
    - ./www:/usr/share/nginx/html:z

