
Vagrant.configure("2") do |config|

  config.vm.define "masternode" do |masternode|
    masternode.vm.box = "centos/7"
    masternode.vm.provider "virtualbox"
    masternode.vm.hostname = "k3smasterbox"
    masternode.vm.synced_folder '.', '/vagrant', disabled: true
    masternode.vm.provision :shell, path: "init_setup.sh", privileged: true
    masternode.vm.network "private_network", ip: "10.205.100.11"
    masternode.vm.network "forwarded_port", guest_ip: "10.205.100.11", guest: 30002, host: 30002, auto_correct: true
    if Vagrant.has_plugin?("vagrant-vbguest")
      masternode.vbguest.auto_update = false
    end
   masternode.vm.provider :virtualbox do |v|
      v.name = "stack_masternode.local"
      v.customize ["modifyvm", :id, "--memory",4000]
      v.customize ["modifyvm", :id, "--cpus", 4]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
  end


  config.vm.define "workernode1" do |workernode1|
    workernode1.vm.box = "centos/7"
    workernode1.vm.hostname = 'workernode1'
    workernode1.vm.synced_folder '.', '/vagrant', disabled: true
    #workernode1.vm.synced_folder VAGRANT_PATH_HOST, VAGRANT_PATH_GUEST, id: "vagrant", mount_options: ["dmode=777,fmode=777"]
    workernode1.vm.network "private_network", ip: "10.205.100.22"
    workernode1.vm.network "forwarded_port", guest_ip: "10.205.100.22", guest: 30002, host: 30002, auto_correct: true

    if Vagrant.has_plugin?("vagrant-vbguest")
      workernode1.vbguest.auto_update = false
    end
    workernode1.vm.provider :virtualbox do |v|
      v.name = "workernode1.ch33.local"
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--cpus", 2]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    workernode1.vm.provision :shell, path: "init_setup.sh", privileged: true
  end

  config.vm.define "workernode2" do |workernode2|
    workernode2.vm.box = "centos/7"
    workernode2.vm.hostname = 'workernode2'
    workernode2.vm.synced_folder '.', '/vagrant', disabled: true
    #workernode2.vm.synced_folder VAGRANT_PATH_HOST, VAGRANT_PATH_GUEST, id: "vagrant", mount_options: ["dmode=777,fmode=777"]
    workernode2.vm.network "private_network", ip: "10.205.100.33"
    workernode2.vm.network "forwarded_port", guest_ip: "10.205.100.33", guest: 30002, host: 30002, auto_correct: true   
    if Vagrant.has_plugin?("vagrant-vbguest")
      workernode2.vbguest.auto_update = false
    end
    workernode2.vm.provider :virtualbox do |v|
      v.name = "workernode2.ch33.local"
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--cpus", 2]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    workernode2.vm.provision :shell, path: "init_setup.sh", privileged: true
  end  

end

