
services:
  app1:
     build: .
     ports:
        - '8085:8080'
     environment:
       - APP_NAME=APP1

  app2:
     build: .
     ports:
        - '8086:8080'
     environment:
       - APP_NAME=APP2

  app3:
     build: .
     ports:
        - '8087:8080'
     environment:
       - APP_NAME=APP3


